//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace 專題Version1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RepaymentAccount
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public RepaymentAccount()
        {
            this.LoanApplications = new HashSet<LoanApplication>();
        }
    
        public int RepaymentAccountID { get; set; }
        public string AccountNumber { get; set; }
        public decimal TotalRepaymentAmount { get; set; }
        public decimal AmountPaid { get; set; }
        public Nullable<decimal> RemainingAmount { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LoanApplication> LoanApplications { get; set; }
    }
}
