//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace 專題Version1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RepaymentSchedule
    {
        public int RepaymentScheduleID { get; set; }
        public int LoanApplicationID { get; set; }
        public System.DateTime RepaymentDate { get; set; }
        public decimal RepaymentAmount { get; set; }
        public string RepaymentStatus { get; set; }
    
        public virtual LoanApplication LoanApplication { get; set; }
    }
}
