//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace 專題Version1.Models.LoanModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class LoanApplication
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public LoanApplication()
        {
            this.RepaymentSchedules = new HashSet<RepaymentSchedule>();
        }
    
        public int LoanApplicationID { get; set; }
        public int CustomerID { get; set; }
        public int LoanProductID { get; set; }
        public System.DateTime ApplicationDate { get; set; }
        public decimal LoanAmount { get; set; }
        public string LoanStatus { get; set; }
        public string EconomicProof { get; set; }
        public string DisbursementAccount { get; set; }
        public Nullable<int> RepaymentMonths { get; set; }
        public Nullable<decimal> TotalRepaymentAmount { get; set; }
        public Nullable<int> RepaymentAccountID { get; set; }
        public Nullable<decimal> InterestRate { get; set; }
    
        public virtual CustomersInLoan CustomersInLoan { get; set; }
        public virtual LoanProduct LoanProduct { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RepaymentSchedule> RepaymentSchedules { get; set; }
        public virtual RepaymentAccount RepaymentAccount { get; set; }
    }
}
