//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace 專題Version1.Models.LoanModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class LoanProduct
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public LoanProduct()
        {
            this.LoanApplications = new HashSet<LoanApplication>();
        }
    
        public int LoanProductID { get; set; }
        public string ProductName { get; set; }
        public decimal InterestRate { get; set; }
        public int LoanTerm { get; set; }
        public decimal MaxLoanAmount { get; set; }
        public decimal MinLoanAmount { get; set; }
        public string ProductDescription { get; set; }
        public string ImageFileName { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LoanApplication> LoanApplications { get; set; }
    }
}
