//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace 專題Version1.Models.LoanModels
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Version3_LoanEntities : DbContext
    {
        public Version3_LoanEntities()
            : base("name=Version3_LoanEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Customer> Customers { get; set; }
        public virtual DbSet<IncomeRangeRate> IncomeRangeRates { get; set; }
        public virtual DbSet<LoanApplication> LoanApplications { get; set; }
        public virtual DbSet<LoanProduct> LoanProducts { get; set; }
        public virtual DbSet<OccupationGroupRate> OccupationGroupRates { get; set; }
        public virtual DbSet<RepaymentAccount> RepaymentAccounts { get; set; }
        public virtual DbSet<RepaymentSchedule> RepaymentSchedules { get; set; }
    }
}
