//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace 專題Version1.Models.LoanModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class OccupationGroupRate
    {
        public int OccupationGroupRateID { get; set; }
        public string OccupationGroup { get; set; }
        public string SubGroup { get; set; }
        public Nullable<decimal> AdjustmentRate { get; set; }
    }
}
