//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace 專題Version1.Models.LoanModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class TransactionLog
    {
        public int TransactionID { get; set; }
        public int RepaymentAccountID { get; set; }
        public System.DateTime TransactionDate { get; set; }
        public string TransactionType { get; set; }
        public decimal Amount { get; set; }
        public System.DateTime CreatedDate { get; set; }
    
        public virtual RepaymentAccount RepaymentAccount { get; set; }
    }
}
